name: Create Release when bootstrap changed
on:
  push:
    branches:
      - master
    paths:
      - 'bootstrap.sh'
      - 'release'
  pull_request:
    branches:
      - master
    paths:
      - 'bootstrap.sh'
      - 'release'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if bootstrap.sh or release changed
        id: check_changes
        run: |
          # Calcula el hash MD5 del contenido anterior y actual de bootstrap.sh
          old_bootstrap_hash=$(git show ${GITHUB_SHA}^:bootstrap.sh | md5sum | awk '{print $1}')
          current_bootstrap_hash=$(git show ${GITHUB_SHA}:bootstrap.sh | md5sum | awk '{print $1}')

          # Calcula el hash MD5 del contenido anterior y actual de release
          old_release_hash=$(git show ${GITHUB_SHA}^:release | md5sum | awk '{print $1}')
          current_release_hash=$(git show ${GITHUB_SHA}:release | md5sum | awk '{print $1}')

          # Compara los hashes para verificar si ha cambiado el contenido
          if [ "$old_bootstrap_hash" != "$current_bootstrap_hash" ] || [ "$old_release_hash" != "$current_release_hash" ]; then
             echo "::set-output name=changed::true"
          else
             echo "::set-output name=changed::false"
          fi

      - name: Read Bin Release Prefix (${{ steps.check_changes.outputs.changed }})
        id: read_release_prefix
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          RELEASE_PREFIX=$(cat release)
          echo "::set-output name=prefix::$RELEASE_PREFIX"

      - name: Create Bin Release
        id: create_release
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: 'v${{ steps.read_release_prefix.outputs.prefix }}.${{ github.run_number }}'
          release_name: 'Release ${{ steps.read_release_prefix.outputs.prefix }}.${{ github.run_number }}'
          body: |
            Changes in bootstrap.sh detected. Automatic release created.
          draft: false
          prerelease: false
          files: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compress repository contents with gzip
        id: create_archive
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git ls-files | xargs gzip -r -k

      - name: Crear distribución de script de instalación bootstrap.sh
        id: upload-release-asset
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Obtener la URL de subida del release creado
          asset_path: ./bootstrap.sh  # Ruta al archivo a subir
          asset_name: bootstrap.sh  # Nombre del archivo en el release
          asset_content_type: application/octet-stream
