name: Espejo en Repositorio Remoto en Panamatech Gitlab

on:
  push:
    branches:
      - master

jobs:
  update-repo-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Panamatech Gitlab Repository (${{ vars.REPO_EMAIL }})
        env:
          token: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "${{ vars.REPO_EMAIL }}"
          git config --global user.name "${{ steps.get-user-info.outputs.full_name }}"
          git remote set-url origin "https://oauth2:${token}@${{ vars.MIRROR_URL }}"
          git push origin HEAD:master

