name: Update Remote Repository on Panamatech Gitdevs
on:
  push:
    branches: [ master ]

jobs:
  update-remote-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Panamatech Gitdevs Repository
        env:
          token: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "mauro.rosero@gmail.com"
          git config --global user.name "Mauro Rosero P."
          git remote set-url origin "https://oauth2:${token}@gitdevs.panamatech.net/mrosero/bin.git"
          git push origin HEAD:master


